name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: ./node_modules/eslint/bin/eslint.js . --ext .js,.jsx,.ts,.tsx
